"""change_types_from_pydantic_uuids_to_standart

Revision ID: 0a01c9682ff0
Revises: 9bf577fdff61
Create Date: 2025-12-31 16:15:10.472239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a01c9682ff0'
down_revision: Union[str, None] = '9bf577fdff61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
