"""add_indexing_jobs

Revision ID: 16bc6a0b5660
Revises: 01b8635ffbc5
Create Date: 2025-11-29 21:29:00.988290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bc6a0b5660'
down_revision: Union[str, None] = '01b8635ffbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexing_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('repository_ids', sa.JSON(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexing_jobs_status'), 'indexing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexing_jobs_status'), table_name='indexing_jobs')
    op.drop_table('indexing_jobs')
    # ### end Alembic commands ###
